---
spring:
  jpa:
    show-sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://132.232.40.116:3306/myspring?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: password

logging:
  config: classpath:log4j2.xml

server:
  servlet:
    context-path: /v1

github:
  client:
    clientId: efcb47787a5ae1052232
    clientSecret: e19819ac6578b87c19e1a0e20eb2e23745ec7947
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope:
      - user
      - repo
  resource:
    userInfoUri: https://api.github.com/user